export const ErrorCode = {
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  REFRESH_EXPIRED: "REFRESH_EXPIRED",
  REFRESH_INVALID: "REFRESH_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  TAG_NAME_TAKEN: "TAG_NAME_TAKEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",
  SHARE_NOT_FOUND: "SHARE_NOT_FOUND",
  SHARE_REVOKED: "SHARE_REVOKED",
  SHARE_EXPIRED: "SHARE_EXPIRED",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
} as const;

export type TErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
